//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kachestvo_vody_v_rodnikakh_permskogo_kraya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Родник.
    /// </summary>
    // *** Start programmer edit section *** (Родник CustomAttributes)

    // *** End programmer edit section *** (Родник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Родник : ICSSoft.STORMNET.DataObject
    {
        
        private string fКоординаты;
        
        // *** Start programmer edit section *** (Родник CustomMembers)

        // *** End programmer edit section *** (Родник CustomMembers)

        
        /// <summary>
        /// Координаты.
        /// </summary>
        // *** Start programmer edit section *** (Родник.Координаты CustomAttributes)

        // *** End programmer edit section *** (Родник.Координаты CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Координаты
        {
            get
            {
                // *** Start programmer edit section *** (Родник.Координаты Get start)

                // *** End programmer edit section *** (Родник.Координаты Get start)
                string result = this.fКоординаты;
                // *** Start programmer edit section *** (Родник.Координаты Get end)

                // *** End programmer edit section *** (Родник.Координаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Родник.Координаты Set start)

                // *** End programmer edit section *** (Родник.Координаты Set start)
                this.fКоординаты = value;
                // *** Start programmer edit section *** (Родник.Координаты Set end)

                // *** End programmer edit section *** (Родник.Координаты Set end)
            }
        }
    }
}
